# Generated by Django 4.2.3 on 2023-08-03 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('unit_exam_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('speaking_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spelling_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verbs_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_exam_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speaking_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spelling_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verbs_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
