# Generated by Django 4.2.3 on 2023-08-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0002_group_alter_task_datecompleted_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='activities',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='plan',
            name='book_pages',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='expected_learning',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='plan',
            name='resources',
            field=models.TextField(max_length=200),
        ),
    ]
