# Generated by Django 4.2.3 on 2023-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0004_alter_plan_activities_alter_plan_book_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
