# Generated by Django 4.2.3 on 2023-08-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0005_alter_plan_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='semana',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
