# Generated by Django 4.2.3 on 2023-08-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0010_alter_calificacion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='user',
        ),
    ]
