# Generated by Django 4.2.3 on 2023-08-14 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0013_alter_plan_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=60)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletas.group'),
        ),
        migrations.CreateModel(
            name='StudentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=60)),
                ('comments', models.TextField(max_length=600)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='boletas.performance')),
            ],
        ),
    ]
