# Generated by Django 4.2.3 on 2023-08-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0017_attendance_attendanceentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
