# Generated by Django 4.2.3 on 2023-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0018_plan_is_submitted_plan_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='week_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='week_start',
            field=models.DateField(null=True),
        ),
    ]
