# Generated by Django 4.2.3 on 2023-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0019_plan_week_end_plan_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performance',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='week_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='week_start',
            field=models.DateField(null=True),
        ),
    ]
