# Generated by Django 4.2.3 on 2023-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0020_performance_is_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='student_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='semana',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
