# Generated by Django 4.2.3 on 2023-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0022_remove_performance_student_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='student_date',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
