# Generated by Django 4.2.3 on 2023-08-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0023_performance_student_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='student_count',
        ),
    ]
