# Generated by Django 4.2.3 on 2023-08-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0024_remove_performance_student_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='student_date',
            new_name='student_data',
        ),
    ]
