# Generated by Django 4.2.3 on 2023-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0025_rename_student_date_performance_student_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='creation_week',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
