# Generated by Django 4.2.3 on 2023-09-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0026_performance_creation_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='creation_week',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='week_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='week_start',
            field=models.DateField(null=True),
        ),
    ]
