# Generated by Django 4.2.3 on 2023-09-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0027_attendance_creation_week_attendance_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10),
        ),
    ]
