# Generated by Django 4.2.3 on 2023-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0028_alter_plan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='creation_week',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='student_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
