# Generated by Django 4.2.3 on 2023-09-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0029_plan_creation_week_plan_student_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionAdult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('unit_exam_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('speaking_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spelling_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verbs_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('writing_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_exam_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speaking_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spelling_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verbs_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('writing_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_porcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
