# Generated by Django 4.2.3 on 2023-10-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0030_calificacionadult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
