# Generated by Django 4.2.3 on 2023-10-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0033_calificacionbabies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceentry',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='boletas.attendance'),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='friday',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='monday',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='student_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='thursday',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='tuesday',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='wednesday',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
