# Generated by Django 4.2.3 on 2023-10-12 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boletas', '0035_responsibilitynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibilitynote',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='responsibilitynote',
            name='week_start',
        ),
        migrations.AlterField(
            model_name='responsibilitynote',
            name='note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='responsibilitynote',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
