# Generated by Django 4.2.3 on 2023-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0039_feedbacknote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_menu', 'Puede ver el menú'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
